# Generated by Django 5.2.15 on 2026-06-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.IntegerField(choices=[(1, 'pv'), (2, 'group_public'), (3, 'group_private')])),
                ('name', models.CharField(max_length=255)),
                ('link', models.SlugField(null=True, unique=True)),
                ('profile', models.ImageField(upload_to='room_profile/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='accounts.profile')),
                ('user', models.ManyToManyField(to='accounts.profile')),
            ],
        ),
    ]
