# Generated by Django 5.2.15 on 2026-07-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='participant',
        ),
    ]
