# Generated by Django 5.2.15 on 2026-07-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='room_profile/'),
        ),
    ]
