# Generated by Django 5.2.15 on 2026-07-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participant',
            new_name='participants',
        ),
    ]
