# Generated by Django 5.2.15 on 2026-07-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_id_alter_profile_user'),
        ('room', '0007_alter_room_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(to='accounts.profile'),
        ),
    ]
