# Generated by Django 5.2.15 on 2026-08-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('room', '0009_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_m', to='message.message'),
        ),
    ]
